### ISSUE TITLE
[Download improvements]Choose download path before starting download,Pause/resume

### ISSUE THREAD

**Issue by Mitia99** [tuyafeng/Via#644] opened 2020-10-31 11:52 UTC
I wonder if you could add an option to set download path before the download starts and add a pause/resume(and indication if the download is resumable or not) feature.Thanks

**Comment by tuyafeng** [comment] 2020-11-05 04:58
I will improve this part. The main reason for this situation is that I need to adapt to android11 ​​first.

**Comment by tuyafeng** [comment] 2022-06-21 08:38
Duplicate of #536

**Closed by tuyafeng** 2022-06-21 08:38 UTC
