### ISSUE TITLE
ANDROID SYSTEM WEBVIEW 81 INCOMPATIBLE WITH VIA BROWSER!

### ISSUE THREAD

**Issue by ShadowMaster85** [tuyafeng/Via#497] opened 2020-05-03 14:56 UTC
I'm having a problem: after updating the Android System Webview to the latest version 81 every time open Via browser a message always appear sayng that the Android System Webview is NOT installed, so is not possible to use Via browser! This problem happen only with the Android System Webview version 81, while this NOT happen with the oldest versions (until version 80) of Android System Webview! I have Android 7.0 and an ARMv7 cpu with 1 Gb ram. What can i do? there is a solution or a fix?

Thanks in advance for any help!

**Comment by stevenfelix505** [comment] 2020-05-05 00:38
Works in ASUS T00I Android 5.0 WebView 81.0.4044.111 using Via Browser 3.9.10
![Screenshot_2020-05-05-07-35-06](https://user-images.githubusercontent.com/57618009/81026080-1b79c500-8ea3-11ea-8e71-0332b44f02d6.jpg)

**Comment by tuyafeng** [comment] 2020-05-05 04:03
Please use the latest stable version of webview, the beta version always has a lot of strange bugs.

**Comment by ShadowMaster85** [comment] 2020-05-05 10:14
Yes, this problem happen with the latest stable version of Android System Webview available on the Play store. What can i do? there is a solution? Thanks!

**Comment by tuyafeng** [comment] 2020-05-06 02:50
Check this: Developer options -> WebView implementation.

**Comment by ShadowMaster85** [comment] 2020-05-06 12:59
Under Developer options -> WebView implementation there is only "Google WebView" option available, wich is already selected. Any solution? Thanks!

**Comment by tuyafeng** [comment] 2020-05-10 03:57
My phone can't reproduce this error, and I'm still looking for the bug. I recommend using the stable webview version 80 first.

**Comment by ShadowMaster85** [comment] 2020-05-11 18:10
Yes, in fact i am using the latest Android System Webview 80, exactly the version 80.0.3987.162 stable form the play store, wich is the latest version working with Via browser for me.

**Comment by ShadowMaster85** [comment] 2020-06-02 12:57
I am having the same problem with the latest Android System Webview 83 stable available on the play store, why this problem still persist also with this new version?
This is the screenshot of the message wich appear every time i open the Via app having installed Android System Webview stable version 81 and 83 from play store, until version 80 it works correctly as usual. Any solution?
![Screenshot_20200602-104537](https://user-images.githubusercontent.com/53215375/83522000-5261eb80-a4e0-11ea-99bb-52671b625147.png)

**Comment by tuyafeng** [comment] 2022-06-21 09:11
This issue will be closed as this question seems outdated.

**Closed by tuyafeng** 2022-06-21 09:11 UTC
