### ISSUE TITLE
[NewFeatureRequest] Print Page

### ISSUE THREAD

**Issue by himawansyahputro** [tuyafeng/Via#663] opened 2020-12-02 03:09 UTC
Print page, just like what google chrome has,
when we choose to "share"

**Comment by Mitia99** [comment] 2020-12-15 08:40
@tuyafeng Maybe a duplicate of #309 but it is a really must-have feature.

**Comment by tuyafeng** [comment] 2021-02-25 14:30
I will close this issue because it is a duplicate, please check #309 .

**Closed** 2021-02-25 14:31 UTC
