### ISSUE TITLE
[NewFeatureRequest] Option to clear/delete cookies per site

### ISSUE THREAD

**Issue by himawansyahputro** [tuyafeng/Via#679] opened 2020-12-10 20:01 UTC
Now in via 4.0.9,
When we choose to clear cookies, we only have the option to clear all cookies and we automatically logged out from logged website

**Comment by Micha-he** [comment] 2020-12-14 07:45
Double ? Look here #433.

**Comment by tuyafeng** [comment] 2020-12-14 14:08
Duplicate of #433

**Closed by tuyafeng** 2020-12-14 14:08 UTC
